<a href="https://colab.research.google.com/github/briskicedteaa/rdkit-cheminformatics-notebooks-/blob/main/02_Molecular_Descriptor_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install rdkit

Requirement already satisfied: rdkit in /usr/local/lib/python3.12/dist-packages (2026.3.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)

In [ ]:
import pandas as pd

df = pd.read_csv('/content/Ligand.csv')

df

        Compound                                         SMILES
0      Caffeine                      Cn1c(=O)c2c(ncn2C)n(C)c1=O
1        Aspirin                          CC(=O)Oc1ccccc1C(=O)O
2  Acetaminophen                          CC(=O)NC1=CC=C(C=C1)O
3     Ibuprofen                   CC(C)CC1=CC=C(C=C1)C(C)C(=O)O
4      Nicotine                            CN1CCC[C@H]1c2cccnc2
5       Dopamine                              NCCc1ccc(O)c(O)c1
6      Serotonin                         NCCc1c[nH]c2ccc(O)cc12
7    Cholesterol  CC(C)CCCC(C)C1CCC2C3CC=C4CC(O)CCC4(C)C3CCC12C
8        Ethanol                                            CCO
9  Invalid Entry                                           C1CC

In [ ]:
from rdkit import Chem

mol1 = Chem.MolFromSmiles("/content/Ligand.csv")
mol1

In [40]:
from rdkit import Chem
from rdkit.Chem import Descriptors

df['NumHeavyAtoms'] = None
df['LogP'] = None
df['HBA'] = None
df['HBD'] = None
df['TPSA'] = None
df['RotatableBonds'] = None
df['NumRings'] = None
df['Parsing Succesful?'] = True

for index, row in df.iterrows():
  compound_name = row['Compound']
  smiles_string = row['SMILES']

  mol = Chem.MolFromSmiles(smiles_string)
  if mol:
    numheavyatoms = mol.GetNumHeavyAtoms()
    logp = Descriptors.MolLogP(mol)
    hba = Descriptors.NumHAcceptors(mol)
    hbd = Descriptors.NumHDonors(mol)
    tpsa = Descriptors.TPSA(mol)
    rot_bonds = Descriptors.NumRotatableBonds(mol)
    numrings = mol.GetRingInfo().NumRings()

    df.loc[index, 'NumHeavyAtoms'] = numheavyatoms
    df.loc[index, 'LogP'] = logp
    df.loc[index, 'HBA'] = hba
    df.loc[index, 'HBD'] = hbd
    df.loc[index, 'TPSA'] = tpsa
    df.loc[index, 'RotatableBonds'] = rot_bonds
    df.loc[index, 'NumRings'] = numrings

  else:
    print(f"Compound {compound_name} (SMILES: {smiles_string}): Invalid SMILES string")
    df.loc[index, 'Parsing Succesful?'] = False

df.drop(['MolWt', 'Molwt', 'SMILES_Valid'], axis=1, inplace = True)

display(df)

Compound Invalid Entry (SMILES: C1CC): Invalid SMILES string

,Compound,SMILES,NumHeavyAtoms,LogP,HBA,HBD,TPSA,RotatableBonds,NumRings,Parsing Succesful?
0,Caffeine,Cn1c(=O)c2c(ncn2C)n(C)c1=O,14,-1.0293,3,0,61.82,0,2,True
1,Aspirin,CC(=O)Oc1ccccc1C(=O)O,13,1.3101,3,1,63.6,2,1,True
2,Acetaminophen,CC(=O)NC1=CC=C(C=C1)O,11,1.3506,2,2,49.33,1,1,True
3,Ibuprofen,CC(C)CC1=CC=C(C=C1)C(C)C(=O)O,15,3.0732,1,1,37.3,4,1,True
4,Nicotine,CN1CCC[C@H]1c2cccnc2,12,1.8483,2,0,16.13,1,2,True
5,Dopamine,NCCc1ccc(O)c(O)c1,11,0.599,3,3,66.48,2,1,True
6,Serotonin,NCCc1c[nH]c2ccc(O)cc12,13,1.3747,2,3,62.04,2,2,True
7,Cholesterol,CC(C)CCCC(C)C1CCC2C3CC=C4CC(O)CCC4(C)C3CCC12C,28,7.3887,1,1,20.23,5,4,True
8,Ethanol,CCO,3,-0.0014,1,1,20.23,0,0,True
9,Invalid Entry,C1CC,None,None,None,None,None,None,None,False

In [ ]:
import pandas as pd

lowest = df[""]