<a href="https://colab.research.google.com/github/briskicedteaa/Acetylcholinesterase-QSAR-ML-/blob/main/03_Molecular_Fingerprints_and_Similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install rdkit
from rdkit import Chem
import pandas as pd

Collecting rdkit
  Downloading rdkit-2026.3.4-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2026.3.4-cp312-cp312-manylinux_2_28_x86_64.whl (37.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.4/37.4 MB 35.6 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2026.3.4

In [ ]:
df = pd.read_csv('/content/Ligand.csv')

df

        Compound                                         SMILES
0      Caffeine                      Cn1c(=O)c2c(ncn2C)n(C)c1=O
1        Aspirin                          CC(=O)Oc1ccccc1C(=O)O
2  Acetaminophen                          CC(=O)NC1=CC=C(C=C1)O
3     Ibuprofen                   CC(C)CC1=CC=C(C=C1)C(C)C(=O)O
4      Nicotine                            CN1CCC[C@H]1c2cccnc2
5       Dopamine                              NCCc1ccc(O)c(O)c1
6      Serotonin                         NCCc1c[nH]c2ccc(O)cc12
7    Cholesterol  CC(C)CCCC(C)C1CCC2C3CC=C4CC(O)CCC4(C)C3CCC12C
8        Ethanol                                            CCO
9  Invalid Entry                                           C1CC

In [20]:
for index, row in df.iterrows():
  compound_name = row['Compound']
  smiles_string = row['SMILES']
  mol = Chem.MolFromSmiles(smiles_string)

display(df)

[21:54:57] SMILES Parse Error: unclosed ring for input: 'C1CC'

        Compound                                         SMILES
0      Caffeine                      Cn1c(=O)c2c(ncn2C)n(C)c1=O
1        Aspirin                          CC(=O)Oc1ccccc1C(=O)O
2  Acetaminophen                          CC(=O)NC1=CC=C(C=C1)O
3     Ibuprofen                   CC(C)CC1=CC=C(C=C1)C(C)C(=O)O
4      Nicotine                            CN1CCC[C@H]1c2cccnc2
5       Dopamine                              NCCc1ccc(O)c(O)c1
6      Serotonin                         NCCc1c[nH]c2ccc(O)cc12
7    Cholesterol  CC(C)CCCC(C)C1CCC2C3CC=C4CC(O)CCC4(C)C3CCC12C
8        Ethanol                                            CCO
9  Invalid Entry                                           C1CC